//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonopolyClient.MonopolySvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonopolySvcRef.IMonopolyService")]
    public interface IMonopolyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonopolyService/GoToJail", ReplyAction="http://tempuri.org/IMonopolyService/GoToJailResponse")]
        void GoToJail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonopolyService/GoToJail", ReplyAction="http://tempuri.org/IMonopolyService/GoToJailResponse")]
        System.Threading.Tasks.Task GoToJailAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonopolyServiceChannel : MonopolyClient.MonopolySvcRef.IMonopolyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonopolyServiceClient : System.ServiceModel.ClientBase<MonopolyClient.MonopolySvcRef.IMonopolyService>, MonopolyClient.MonopolySvcRef.IMonopolyService {
        
        public MonopolyServiceClient() {
        }
        
        public MonopolyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonopolyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonopolyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonopolyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GoToJail() {
            base.Channel.GoToJail();
        }
        
        public System.Threading.Tasks.Task GoToJailAsync() {
            return base.Channel.GoToJailAsync();
        }
    }
}
